steps:
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker build -t us-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/portfolio-image:tag1 .
    automapSubstitutions: true
images:
  - "us-south1-docker.pkg.dev/portfolio/docker-repo/portfolio-image:tag1"
